## Detect platform and create `CCG_PLATFORM_DEFINITIONS` variable
message(TRACE "ccg::DetectPlatform")


set(CCG_PLATFORM_DEFINITIONS "")


# Platform
message(TRACE "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(CCG_PLATFORM_LINUX     TRUE)
    set(CCG_PLATFORM_WINDOWS   FALSE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_PLATFORM_LINUX")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(CCG_PLATFORM_LINUX     FALSE)
    set(CCG_PLATFORM_WINDOWS   TRUE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_PLATFORM_WINDOWS")

else()
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()


# Compiler
message(TRACE "CMAKE_CXX_COMPILER:                  ${CMAKE_CXX_COMPILER}")
message(TRACE "CMAKE_CXX_COMPILER_ID:               ${CMAKE_CXX_COMPILER_ID}")
message(TRACE "CMAKE_CXX_COMPILER_FRONTEND_VARIANT: ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")
message(TRACE "CMAKE_CXX_COMPILER_VERSION:          ${CMAKE_CXX_COMPILER_VERSION}")

if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang.*" AND CCG_PLATFORM_LINUX)
    set(CCG_COMPILER_CLANG     TRUE)
    set(CCG_COMPILER_CLANGCL   FALSE)
    set(CCG_COMPILER_GCC       FALSE)
    set(CCG_COMPILER_MSVC      FALSE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_COMPILER_CLANG")

elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang.*" AND CCG_PLATFORM_WINDOWS)
    set(CCG_COMPILER_CLANG     FALSE)
    set(CCG_COMPILER_CLANGCL   TRUE)
    set(CCG_COMPILER_GCC       FALSE)
    set(CCG_COMPILER_MSVC      FALSE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_COMPILER_CLANG")

elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*GNU.*")
    set(CCG_COMPILER_CLANG     FALSE)
    set(CCG_COMPILER_CLANGCL   FALSE)
    set(CCG_COMPILER_GCC       TRUE)
    set(CCG_COMPILER_MSVC      FALSE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_COMPILER_GCC")

elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(CCG_COMPILER_CLANG     FALSE)
    set(CCG_COMPILER_CLANGCL   FALSE)
    set(CCG_COMPILER_GCC       FALSE)
    set(CCG_COMPILER_MSVC      TRUE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_COMPILER_MSVC")

    message(TRACE "CCG_COMPILER_MSVC_VERSION: ${CCG_COMPILER_MSVC_VERSION}")
    set(CCG_COMPILER_MSVC_VERSION ${MSVC_VERSION})
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_COMPILER_MSVC_VERSION=${MSVC_VERSION}")

else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()


# C++ Standard Version
message(TRACE "CMAKE_CXX_STANDARD: ${CMAKE_CXX_STANDARD}")

if (CMAKE_CXX_STANDARD STREQUAL "23")
    set(CCG_STD_VERSION 23)
    list(APPEND CCG_HAS_CXX23)
    list(APPEND CCG_HAS_CXX20)
    list(APPEND CCG_HAS_CXX17)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_HAS_CXX17" "CCG_HAS_CXX20" "CCG_HAS_CXX23")

elseif(CMAKE_CXX_STANDARD STREQUAL "20")
    list(APPEND CCG_HAS_CXX20)
    list(APPEND CCG_HAS_CXX17)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_HAS_CXX17" "CCG_HAS_CXX20")

elseif(CMAKE_CXX_STANDARD STREQUAL "17")
    list(APPEND CCG_HAS_CXX17)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_HAS_CXX17")

else()
    message(FATAL_ERROR "Unknown CXX standard: ${CMAKE_CXX_STANDARD}")
endif()


# Build variant
message(TRACE "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CCG_BUILD_DEBUG        TRUE)
    set(CCG_BUILD_RELEASE      FALSE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_BUILD_DEBUG")

elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo" OR CMAKE_BUILD_TYPE STREQUAL "Release")
    set(CCG_BUILD_DEBUG        FALSE)
    set(CCG_BUILD_RELEASE      TRUE)
    list(APPEND CCG_PLATFORM_DEFINITIONS "CCG_BUILD_RELEASE")

else()
    message(FATAL_ERROR "Unknown build type: ${CMAKE_BUILD_TYPE}")
endif()


message(STATUS "CCG platform definitions:")

foreach(DEF IN LISTS CCG_PLATFORM_DEFINITIONS)
    message(STATUS "  ${DEF}")
endforeach()
